### ISSUE TITLE
non static hashFunc_

### ISSUE THREAD

**Issue by deGekata** [deGekata/SummerSchool2021#3]
/*--------------Second-------------*/
    #if PROTECTION_LEVEL == HASH or PROTECTION_LEVEL == FULL_PROTECTION
        //int64_t hashFunc_(const char * str, size_t len, int64_t init);
        SafeStackHashes* makeHash_(SafeStack* st);
        stack.arr[2] = 10;
        stack.hash = *(int64_t*)makeHash_(&stack); 
    #endif
    /*--------------------------------*/

**Comment by DarkSoulEater** [comment]
Ok, bro
